Description: >-
  UnionAI Management CloudFormation Template: This CloudFormation template is responsible for creating a management IAM role that UnionAI will utilize. This role is intended for management purposes and
  does not grant permissions for creating, deleting, tagging, or untagging resources. Its purpose is to provide necessary access for efficiently managing UnionAI resources.
Resources:
  CrossAccountRoleForAWSTrustedAdvisorUnion:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::479331373192:root
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Ref 'UnionaiReaderPermission'
        - !Ref 'UnionaiManagerPermission'
        - !Ref 'UnionaiAdminPermission'
      RoleName: unionai-manager-role
    Type: AWS::IAM::Role
  UnionaiAdminPermission:
    Properties:
      ManagedPolicyName: admin-policy-for-manager-role
      PolicyDocument:
        Statement:
          - Action:
              - eks:CreateNodegroup
              - eks:TagResource
              - eks:UntagResource
              - eks:DeleteNodegroup
            Effect: Allow
            Resource:
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/opta-*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*'
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - arn:aws:s3:::opta-*
          - Action:
              - iam:CreateServiceLinkedRole
              - iam:PassRole
            Effect: Allow
            Resource:
              - '!Sub arn:aws:iam::${AWS::AccountId}:policy/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:role/*'
          - Action:
              - autoscaling:CreateOrUpdateTags
              - autoscaling:DeleteTags
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - ec2:EnableEbsEncryptionByDefault
              - ec2:GetEbsEncryptionByDefault
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - dynamodb:*
            Effect: Allow
            Resource:
              - '!Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/opta-*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  UnionaiManagerPermission:
    Properties:
      ManagedPolicyName: manager-policy-for-manager-role
      PolicyDocument:
        Statement:
          - Action:
              - ec2:ModifyEbsDefaultKmsKeyId
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowModifyEbsDefaultKmsKeyId
          - Action:
              - ec2:ModifyVpcEndpoint
              - ec2:ModifyVpcAttribute
              - ec2:ModifySubnetAttribute
            Effect: Allow
            Resource:
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:internet-gateway/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:elastic-ip/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:natgateway/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:route-table/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/subnet-*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group-rule/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc-flow-log/*'
              - '!Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/*'
            Sid: AllowModifyVpcEndpoint
          - Action:
              - ec2:ModifyLaunchTemplate
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowModifyLaunchTemplate
          - Action:
              - eks:UpdateNodegroupConfig
              - eks:UpdateNodegroupVersion
              - eks:UpdateClusterConfig
              - eks:UpdateClusterVersion
            Effect: Allow
            Resource:
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/opta-*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*'
            Sid: AllowUpdateClusterConfig
          - Action:
              - eks:CreateAddon
              - eks:UpdateAddon
              - eks:DeleteAddon
              - eks:DescribeAddonVersions
              - eks:DescribeAddon
              - eks:ListAddons
            Effect: Allow
            Resource:
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/opta-*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:addon/opta-*/*/*'
            Sid: AllowUpdateAddon
          - Action:
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:CreateOrUpdateTags
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowUpdateAutoScalingGroup
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  UnionaiReaderPermission:
    Properties:
      ManagedPolicyName: reader-policy-for-manager-role
      PolicyDocument:
        Statement:
          - Action:
              - logs:DescribeLogGroups
              - logs:DescribeDBSubnetGroups
              - logs:DescribeLogStreams
            Effect: Allow
            Resource:
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:opta-*'
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group::log-stream*'
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/eks/opta-*:*'
            Sid: AllowDescribeLogGroups
          - Action:
              - logs:ListTagsLogGroup
            Effect: Allow
            Resource:
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:opta-*'
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group::log-stream*'
              - '!Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/eks/opta-*:*'
            Sid: AllowListTagsLogGroup
          - Action:
              - s3:GetBucketLogging
              - s3:GetAccelerateConfiguration
              - s3:GetBucketAcl
              - s3:GetBucketCORS
            Effect: Allow
            Resource:
              - arn:aws:s3:::opta-*
            Sid: AllowGetBucketLogging
          - Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeScalingActivities
              - autoscaling:DescribeTags
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowDescribeAutoScalingGroups
          - Action:
              - eks:DescribeCluster
              - eks:DescribeNodegroup
              - eks:DescribeUpdate
            Effect: Allow
            Resource:
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/opta-*!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
            Sid: AllowDescribeCluster
          - Action:
              - eks:ListTagsForResource
              - eks:ListNodegroups
              - eks:ListTagsForResource
            Effect: Allow
            Resource:
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/opta-*!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
              - '!Sub arn:aws:eks:${AWS::Region}:${AWS::AccountId}:nodegroup/opta-*/opta-*/*'
            Sid: AllowListTagsForEKS
          - Action:
              - kms:GetKeyPolicy
              - kms:GetKeyRotationStatus
              - kms:DescribeKey
            Effect: Allow
            Resource:
              - '!Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/*'
              - '!Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
            Sid: AllowGetKeyPolicy
          - Action:
              - kms:ListResourceTags
              - kms:ListAliases
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowListResourceTags
          - Action:
              - iam:GetOpenIDConnectProvider
              - iam:GetPolicyVersion
              - iam:GetPolicy
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:GetInstanceProfile
            Effect: Allow
            Resource:
              - '!Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:policy/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:role/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*'
            Sid: AllowGetIAM
          - Action:
              - iam:ListOpenIDConnectProviderTags
              - iam:ListPolicyVersions
              - iam:ListPolicyTags
              - iam:ListRoleTags
              - iam:ListInstanceProfilesForRole
              - iam:ListInstanceProfileTags
              - iam:ListRoles
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
            Effect: Allow
            Resource:
              - '!Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:policy/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:role/*'
              - '!Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*'
            Sid: AllowListIAM
          - Action:
              - ec2:DescribeAccountAttributes
              - ec2:DescribeAddresses
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeFlowLogs
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeInternetGateways
              - ec2:DescribeNatGateways
              - ec2:DescribeNetworkAcls
              - ec2:AssociateAddress
              - ec2:DisassociateAddress
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribePrefixLists
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroupRules
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcAttribute
              - ec2:DescribeVpcClassicLink
              - ec2:DescribeVpcClassicLinkDnsSupport
              - ec2:DescribeVpcEndpoints
              - ec2:DescribeVpcs
              - ec2:DescribeImages
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeLaunchTemplateVersions
              - ec2:GetEbsEncryptionByDefault
            Effect: Allow
            Resource:
              - '*'
            Sid: AllowDescribeAccountAttributes
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
