# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: UC CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint
        run: |
          black --check union-ai-admin/aws/script/generate.py
        env:
          PYTHONPATH: $(pwd)

  cf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint
        run: |
          cfn-lint ./union-ai-admin/aws/*.yaml
        env:
          PYTHONPATH: $(pwd)
